[project]
name = "tgstatviz"
version = "0.1.0"
description = ""
authors = [
    { name = "vplotnikov16", email = "vplotnikov16@yandex.ru" }
]
readme = "README.md"
requires-python = ">=3.10,<3.11"

dependencies = [
    "poetry-core (>=2.0.0)",
    "pyyaml (>=6.0.3)",
    "manim (>=0.19.1)",
    "pylint (>=4.0.4)"
]

[dependency-groups]
dev = [
    "pytest (>=9.0.2,<10.0.0)",
    "pylint (>=4.0.4,<5.0.0)"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "-v",
    "--strict-markers",
    "--tb=short",
    "--disable-warnings"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
